parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     sdz_symfony
    database_user:     root
    database_password: ~

    mailer_transport:  gmail
    mailer_host:       
    mailer_user:       gandiol.r512@gmail.com
    mailer_password:   Chiffon1

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
