<?php

namespace Sdz\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ArticleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sdz\BlogBundle\Controller\ArticleController();
        return $instance;
    }
}
